# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge packages over pip as installations are more efficient.
  - python=3.9.13               # https://pyreadiness.org/3.9/ 
  - pip=22.1.2                  # https://pip.pypa.io/en/stable/news/
  - pip:
      # Define pip packages here -> https://pypi.org/
      - rpaframework==22.0.0    # https://rpaframework.org/releasenotes.html
      # Add some pytest deps so that testing works in the same environment.
      - pytest
      - pytest-regressions==1.0.6
      - pytest-xdist
      - pytest-timeout
      
      # Code formatting in this environment.
      - black==22.12.0
      
      # Typing in this environment.
      - mypy==1.1.1

