# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProcessRunIdStopBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'set_remaining_work_items_as_done': 'bool',
        'terminate_ongoing_activity_runs': 'bool',
        'reason': 'str'
    }

    attribute_map = {
        'set_remaining_work_items_as_done': 'set_remaining_work_items_as_done',
        'terminate_ongoing_activity_runs': 'terminate_ongoing_activity_runs',
        'reason': 'reason'
    }

    def __init__(self, set_remaining_work_items_as_done=None, terminate_ongoing_activity_runs=None, reason=None):  # noqa: E501
        """ProcessRunIdStopBody - a model defined in Swagger"""  # noqa: E501
        self._set_remaining_work_items_as_done = None
        self._terminate_ongoing_activity_runs = None
        self._reason = None
        self.discriminator = None
        self.set_remaining_work_items_as_done = set_remaining_work_items_as_done
        self.terminate_ongoing_activity_runs = terminate_ongoing_activity_runs
        if reason is not None:
            self.reason = reason

    @property
    def set_remaining_work_items_as_done(self):
        """Gets the set_remaining_work_items_as_done of this ProcessRunIdStopBody.  # noqa: E501


        :return: The set_remaining_work_items_as_done of this ProcessRunIdStopBody.  # noqa: E501
        :rtype: bool
        """
        return self._set_remaining_work_items_as_done

    @set_remaining_work_items_as_done.setter
    def set_remaining_work_items_as_done(self, set_remaining_work_items_as_done):
        """Sets the set_remaining_work_items_as_done of this ProcessRunIdStopBody.


        :param set_remaining_work_items_as_done: The set_remaining_work_items_as_done of this ProcessRunIdStopBody.  # noqa: E501
        :type: bool
        """
        if set_remaining_work_items_as_done is None:
            raise ValueError("Invalid value for `set_remaining_work_items_as_done`, must not be `None`")  # noqa: E501

        self._set_remaining_work_items_as_done = set_remaining_work_items_as_done

    @property
    def terminate_ongoing_activity_runs(self):
        """Gets the terminate_ongoing_activity_runs of this ProcessRunIdStopBody.  # noqa: E501


        :return: The terminate_ongoing_activity_runs of this ProcessRunIdStopBody.  # noqa: E501
        :rtype: bool
        """
        return self._terminate_ongoing_activity_runs

    @terminate_ongoing_activity_runs.setter
    def terminate_ongoing_activity_runs(self, terminate_ongoing_activity_runs):
        """Sets the terminate_ongoing_activity_runs of this ProcessRunIdStopBody.


        :param terminate_ongoing_activity_runs: The terminate_ongoing_activity_runs of this ProcessRunIdStopBody.  # noqa: E501
        :type: bool
        """
        if terminate_ongoing_activity_runs is None:
            raise ValueError("Invalid value for `terminate_ongoing_activity_runs`, must not be `None`")  # noqa: E501

        self._terminate_ongoing_activity_runs = terminate_ongoing_activity_runs

    @property
    def reason(self):
        """Gets the reason of this ProcessRunIdStopBody.  # noqa: E501


        :return: The reason of this ProcessRunIdStopBody.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ProcessRunIdStopBody.


        :param reason: The reason of this ProcessRunIdStopBody.  # noqa: E501
        :type: str
        """

        self._reason = reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProcessRunIdStopBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProcessRunIdStopBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
