# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkerGroupLinkTokenResource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'expires_at': 'datetime',
        'worker_group': 'WorkspacesworkspaceIdworkergroupsworkerGroupIdworkersWorker'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'expires_at': 'expires_at',
        'worker_group': 'worker_group'
    }

    def __init__(self, id=None, name=None, expires_at=None, worker_group=None):  # noqa: E501
        """WorkerGroupLinkTokenResource - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._expires_at = None
        self._worker_group = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.expires_at = expires_at
        self.worker_group = worker_group

    @property
    def id(self):
        """Gets the id of this WorkerGroupLinkTokenResource.  # noqa: E501


        :return: The id of this WorkerGroupLinkTokenResource.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WorkerGroupLinkTokenResource.


        :param id: The id of this WorkerGroupLinkTokenResource.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this WorkerGroupLinkTokenResource.  # noqa: E501


        :return: The name of this WorkerGroupLinkTokenResource.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WorkerGroupLinkTokenResource.


        :param name: The name of this WorkerGroupLinkTokenResource.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def expires_at(self):
        """Gets the expires_at of this WorkerGroupLinkTokenResource.  # noqa: E501


        :return: The expires_at of this WorkerGroupLinkTokenResource.  # noqa: E501
        :rtype: datetime
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at):
        """Sets the expires_at of this WorkerGroupLinkTokenResource.


        :param expires_at: The expires_at of this WorkerGroupLinkTokenResource.  # noqa: E501
        :type: datetime
        """
        if expires_at is None:
            raise ValueError("Invalid value for `expires_at`, must not be `None`")  # noqa: E501

        self._expires_at = expires_at

    @property
    def worker_group(self):
        """Gets the worker_group of this WorkerGroupLinkTokenResource.  # noqa: E501


        :return: The worker_group of this WorkerGroupLinkTokenResource.  # noqa: E501
        :rtype: WorkspacesworkspaceIdworkergroupsworkerGroupIdworkersWorker
        """
        return self._worker_group

    @worker_group.setter
    def worker_group(self, worker_group):
        """Sets the worker_group of this WorkerGroupLinkTokenResource.


        :param worker_group: The worker_group of this WorkerGroupLinkTokenResource.  # noqa: E501
        :type: WorkspacesworkspaceIdworkergroupsworkerGroupIdworkersWorker
        """
        if worker_group is None:
            raise ValueError("Invalid value for `worker_group`, must not be `None`")  # noqa: E501

        self._worker_group = worker_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkerGroupLinkTokenResource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkerGroupLinkTokenResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
