# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkerToGroupLinkListing(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'worker': 'WorkspacesworkspaceIdworkergroupsworkerGroupIdworkersWorker',
        'worker_groups': 'list[InlineResponse20024]'
    }

    attribute_map = {
        'worker': 'worker',
        'worker_groups': 'worker_groups'
    }

    def __init__(self, worker=None, worker_groups=None):  # noqa: E501
        """WorkerToGroupLinkListing - a model defined in Swagger"""  # noqa: E501
        self._worker = None
        self._worker_groups = None
        self.discriminator = None
        self.worker = worker
        self.worker_groups = worker_groups

    @property
    def worker(self):
        """Gets the worker of this WorkerToGroupLinkListing.  # noqa: E501


        :return: The worker of this WorkerToGroupLinkListing.  # noqa: E501
        :rtype: WorkspacesworkspaceIdworkergroupsworkerGroupIdworkersWorker
        """
        return self._worker

    @worker.setter
    def worker(self, worker):
        """Sets the worker of this WorkerToGroupLinkListing.


        :param worker: The worker of this WorkerToGroupLinkListing.  # noqa: E501
        :type: WorkspacesworkspaceIdworkergroupsworkerGroupIdworkersWorker
        """
        if worker is None:
            raise ValueError("Invalid value for `worker`, must not be `None`")  # noqa: E501

        self._worker = worker

    @property
    def worker_groups(self):
        """Gets the worker_groups of this WorkerToGroupLinkListing.  # noqa: E501


        :return: The worker_groups of this WorkerToGroupLinkListing.  # noqa: E501
        :rtype: list[InlineResponse20024]
        """
        return self._worker_groups

    @worker_groups.setter
    def worker_groups(self, worker_groups):
        """Sets the worker_groups of this WorkerToGroupLinkListing.


        :param worker_groups: The worker_groups of this WorkerToGroupLinkListing.  # noqa: E501
        :type: list[InlineResponse20024]
        """
        if worker_groups is None:
            raise ValueError("Invalid value for `worker_groups`, must not be `None`")  # noqa: E501

        self._worker_groups = worker_groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkerToGroupLinkListing, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkerToGroupLinkListing):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
