channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pip=22.1.2
  - pip:
      - requests
      - playwright
      - tomli>=2.0.1,<3
      - pillow
      - xlrd
      - xlwt
      - xlutils
      - openpyxl
      - typing-extensions
      - robocorp-http==0.4.0
