# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

import pydantic


from pydantic import BaseModel, Field
from robocorp.workspace.models.generic_error_response_error import GenericErrorResponseError

class GenericErrorResponse(BaseModel):
    """
    GenericErrorResponse
    """
    error: GenericErrorResponseError = Field(...)
    __properties = ["error"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GenericErrorResponse:
        """Create an instance of GenericErrorResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GenericErrorResponse:
        """Create an instance of GenericErrorResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GenericErrorResponse.parse_obj(obj)

        _obj = GenericErrorResponse.parse_obj({
            "error": GenericErrorResponseError.from_dict(obj.get("error")) if obj.get("error") is not None else None
        })
        return _obj


