# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

import pydantic


from pydantic import BaseModel, Field, StrictStr

class ProcessRunResourceStartedByDetails(BaseModel):
    """
    Details are only available when the process run was started by a `user`  # noqa: E501
    """
    id: StrictStr = Field(...)
    first_name: StrictStr = Field(...)
    last_name: StrictStr = Field(...)
    __properties = ["id", "first_name", "last_name"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProcessRunResourceStartedByDetails:
        """Create an instance of ProcessRunResourceStartedByDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProcessRunResourceStartedByDetails:
        """Create an instance of ProcessRunResourceStartedByDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProcessRunResourceStartedByDetails.parse_obj(obj)

        _obj = ProcessRunResourceStartedByDetails.parse_obj({
            "id": obj.get("id"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name")
        })
        return _obj


