# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional
from pydantic import BaseModel, StrictStr, field_validator
from pydantic import StrictStr, StrictBool
from pydantic import Field
from robocorp.workspace.models.task_package_resource_download import TaskPackageResourceDownload
from robocorp.workspace.models.update_worker_request import UpdateWorkerRequest
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TaskPackageResource(BaseModel):
    """
    TaskPackageResource
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    type: StrictStr
    tasks: List[UpdateWorkerRequest] = Field(description="Tasks contained in the task package: empty array if the task package has not been uploaded yet.")
    download: Optional[TaskPackageResourceDownload]
    __properties: ClassVar[List[str]] = ["id", "name", "type", "tasks", "download"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('zip'):
            raise ValueError("must be one of enum values ('zip')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TaskPackageResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tasks (list)
        _items = []
        if self.tasks:
            for _item in self.tasks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tasks'] = _items
        # override the default output from pydantic by calling `to_dict()` of download
        if self.download:
            _dict['download'] = self.download.to_dict()
        # set to None if download (nullable) is None
        # and model_fields_set contains the field
        if self.download is None and "download" in self.model_fields_set:
            _dict['download'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TaskPackageResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "tasks": [UpdateWorkerRequest.from_dict(_item) for _item in obj.get("tasks")] if obj.get("tasks") is not None else None,
            "download": TaskPackageResourceDownload.from_dict(obj.get("download")) if obj.get("download") is not None else None
        })
        return _obj


