# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class WorkItemState(str, Enum):
    """
    WorkItemState
    """

    """
    allowed enum values
    """
    NEW = 'new'
    PENDING = 'pending'
    IN_PROGRESS = 'in_progress'
    FAILED = 'failed'
    DONE = 'done'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkItemState from a JSON string"""
        return cls(json.loads(json_str))


