# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.any_valid_json_optional import AnyValidJsonOptional  # noqa: E501
from swagger_client.rest import ApiException


class TestAnyValidJsonOptional(unittest.TestCase):
    """AnyValidJsonOptional unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyValidJsonOptional(self):
        """Test AnyValidJsonOptional"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.any_valid_json_optional.AnyValidJsonOptional()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
