# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.assistant_run_resource_error import AssistantRunResourceError  # noqa: E501
from swagger_client.rest import ApiException


class TestAssistantRunResourceError(unittest.TestCase):
    """AssistantRunResourceError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssistantRunResourceError(self):
        """Test AssistantRunResourceError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.assistant_run_resource_error.AssistantRunResourceError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
