# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.step_run_api import StepRunApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStepRunApi(unittest.TestCase):
    """StepRunApi unit test stubs"""

    def setUp(self):
        self.api = StepRunApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_step_run(self):
        """Test case for get_step_run

        Get step run  # noqa: E501
        """
        pass

    def test_get_step_run_artifact(self):
        """Test case for get_step_run_artifact

        Get step run artifact  # noqa: E501
        """
        pass

    def test_list_step_run_artifacts(self):
        """Test case for list_step_run_artifacts

        List step run artifacts  # noqa: E501
        """
        pass

    def test_list_step_run_console_messages(self):
        """Test case for list_step_run_console_messages

        List step run console messages  # noqa: E501
        """
        pass

    def test_list_step_run_events(self):
        """Test case for list_step_run_events

        List step run events  # noqa: E501
        """
        pass

    def test_list_step_runs(self):
        """Test case for list_step_runs

        List step runs of process run  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
