# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.webhook_enabled_events import WebhookEnabledEvents  # noqa: E501
from swagger_client.rest import ApiException


class TestWebhookEnabledEvents(unittest.TestCase):
    """WebhookEnabledEvents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhookEnabledEvents(self):
        """Test WebhookEnabledEvents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.webhook_enabled_events.WebhookEnabledEvents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
