# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.workers_worker_id_body import WorkersWorkerIdBody  # noqa: E501
from swagger_client.rest import ApiException


class TestWorkersWorkerIdBody(unittest.TestCase):
    """WorkersWorkerIdBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkersWorkerIdBody(self):
        """Test WorkersWorkerIdBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.workers_worker_id_body.WorkersWorkerIdBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
