# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.asset_api import AssetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAssetApi(unittest.TestCase):
    """AssetApi unit test stubs"""

    def setUp(self):
        self.api = AssetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_asset(self):
        """Test case for create_asset

        Create new asset  # noqa: E501
        """
        pass

    def test_create_asset_upload(self):
        """Test case for create_asset_upload

        Create asset upload  # noqa: E501
        """
        pass

    def test_delete_asset(self):
        """Test case for delete_asset

        Delete asset  # noqa: E501
        """
        pass

    def test_get_asset(self):
        """Test case for get_asset

        Get asset  # noqa: E501
        """
        pass

    def test_get_asset_upload(self):
        """Test case for get_asset_upload

        Get asset upload  # noqa: E501
        """
        pass

    def test_list_assets(self):
        """Test case for list_assets

        List assets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
