# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.assistant_run_resource import AssistantRunResource  # noqa: E501
from swagger_client.rest import ApiException


class TestAssistantRunResource(unittest.TestCase):
    """AssistantRunResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssistantRunResource(self):
        """Test AssistantRunResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.assistant_run_resource.AssistantRunResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
