name: 🐛 Bug report
description: Submit a bug report to help us make Robocorp better
labels: [ bug ]
body:
  - type: dropdown
    id: components
    attributes:
      label: Target components
      description: Select the affected packages in the reported bug
      multiple: true
      options:
        - Other
        - action_server
        - actions
        - browser
        - desktop
        - devutils
        - docs
        - excel
        - integration_tests
        - log
        - log_pytest
        - meta
        - storage
        - tasks
        - templates
        - vault
        - windows
        - workitems
      default: 0
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What happened?
      description: >-
        Give details on what you are doing, what you expect to happen, and what
        is currently happening.
      placeholder: >-
        * I'm trying to use the `robocorp` library to do X
        * I'expected to get Y
        * Instead it does Z
    validations:
      required: true
  - type: textarea
    id: system
    attributes:
      label: System Info
      description: Sharing your system information will help us a lot
      placeholder: >-
        * Library version
        * Python version
        * Operating System version
    validations:
      required: true
