name: ⭐️ Feature Request
description: Submit a proposal/request for a new feature
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the problem or the missing capability
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like to see
      description: If you have a solution in mind, please detail it.
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: Are you using or have you considered any alternative solutions or workarounds?
