# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.list_process_run_work_items200_response_data_inner_step_run import ListProcessRunWorkItems200ResponseDataInnerStepRun  # noqa: E501

class TestListProcessRunWorkItems200ResponseDataInnerStepRun(unittest.TestCase):
    """ListProcessRunWorkItems200ResponseDataInnerStepRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListProcessRunWorkItems200ResponseDataInnerStepRun:
        """Test ListProcessRunWorkItems200ResponseDataInnerStepRun
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListProcessRunWorkItems200ResponseDataInnerStepRun`
        """
        model = ListProcessRunWorkItems200ResponseDataInnerStepRun()  # noqa: E501
        if include_optional:
            return ListProcessRunWorkItems200ResponseDataInnerStepRun(
                id = ''
            )
        else:
            return ListProcessRunWorkItems200ResponseDataInnerStepRun(
                id = '',
        )
        """

    def testListProcessRunWorkItems200ResponseDataInnerStepRun(self):
        """Test ListProcessRunWorkItems200ResponseDataInnerStepRun"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
