# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace.models.list_webhooks200_response_data_inner_process import ListWebhooks200ResponseDataInnerProcess  # noqa: E501

class TestListWebhooks200ResponseDataInnerProcess(unittest.TestCase):
    """ListWebhooks200ResponseDataInnerProcess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWebhooks200ResponseDataInnerProcess:
        """Test ListWebhooks200ResponseDataInnerProcess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWebhooks200ResponseDataInnerProcess`
        """
        model = ListWebhooks200ResponseDataInnerProcess()  # noqa: E501
        if include_optional:
            return ListWebhooks200ResponseDataInnerProcess(
                id = ''
            )
        else:
            return ListWebhooks200ResponseDataInnerProcess(
                id = '',
        )
        """

    def testListWebhooks200ResponseDataInnerProcess(self):
        """Test ListWebhooks200ResponseDataInnerProcess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
