# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace.models.create_work_item_request import CreateWorkItemRequest  # noqa: E501

class TestCreateWorkItemRequest(unittest.TestCase):
    """CreateWorkItemRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWorkItemRequest:
        """Test CreateWorkItemRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWorkItemRequest`
        """
        model = CreateWorkItemRequest()  # noqa: E501
        if include_optional:
            return CreateWorkItemRequest(
                process = workspace.models.add_worker_to_group_request_worker.addWorkerToGroup_request_worker(
                    id = '', ),
                payload = None
            )
        else:
            return CreateWorkItemRequest(
                process = workspace.models.add_worker_to_group_request_worker.addWorkerToGroup_request_worker(
                    id = '', ),
                payload = None,
        )
        """

    def testCreateWorkItemRequest(self):
        """Test CreateWorkItemRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
