# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace.models.webhook_resource import WebhookResource  # noqa: E501

class TestWebhookResource(unittest.TestCase):
    """WebhookResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookResource:
        """Test WebhookResource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookResource`
        """
        model = WebhookResource()  # noqa: E501
        if include_optional:
            return WebhookResource(
                id = '',
                process = workspace.models.list_webhooks_200_response_data_inner_process.listWebhooks_200_response_data_inner_process(
                    id = '', ),
                enabled_events = [
                    ''
                    ],
                secret = '',
                endpoint = ''
            )
        else:
            return WebhookResource(
                id = '',
                process = workspace.models.list_webhooks_200_response_data_inner_process.listWebhooks_200_response_data_inner_process(
                    id = '', ),
                enabled_events = [
                    ''
                    ],
                secret = '',
                endpoint = '',
        )
        """

    def testWebhookResource(self):
        """Test WebhookResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
