# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace.models.assistant_resource import AssistantResource  # noqa: E501

class TestAssistantResource(unittest.TestCase):
    """AssistantResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssistantResource:
        """Test AssistantResource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssistantResource`
        """
        model = AssistantResource()  # noqa: E501
        if include_optional:
            return AssistantResource(
                id = '',
                name = '',
                task = workspace.models.assistant_resource_task.AssistantResource_task(
                    package_id = '', 
                    name = '', ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AssistantResource(
                id = '',
                name = '',
                task = workspace.models.assistant_resource_task.AssistantResource_task(
                    package_id = '', 
                    name = '', ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testAssistantResource(self):
        """Test AssistantResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
