# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace.api.workspace_api import WorkspaceApi  # noqa: E501


class TestWorkspaceApi(unittest.TestCase):
    """WorkspaceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspaceApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_workspace(self) -> None:
        """Test case for get_workspace

        Get workspace  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
