# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace.models.list_step_run_events200_response import ListStepRunEvents200Response  # noqa: E501

class TestListStepRunEvents200Response(unittest.TestCase):
    """ListStepRunEvents200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListStepRunEvents200Response:
        """Test ListStepRunEvents200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListStepRunEvents200Response`
        """
        model = ListStepRunEvents200Response()  # noqa: E501
        if include_optional:
            return ListStepRunEvents200Response(
                next = None,
                has_more = None,
                data = [
                    workspace.models.list_step_run_events_200_response_data_inner.listStepRunEvents_200_response_data_inner(
                        timestamp = '', 
                        event_type = '', )
                    ]
            )
        else:
            return ListStepRunEvents200Response(
                next = None,
                has_more = None,
                data = [
                    workspace.models.list_step_run_events_200_response_data_inner.listStepRunEvents_200_response_data_inner(
                        timestamp = '', 
                        event_type = '', )
                    ],
        )
        """

    def testListStepRunEvents200Response(self):
        """Test ListStepRunEvents200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
