# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace.models.create_worker_group_link_token_request import CreateWorkerGroupLinkTokenRequest  # noqa: E501

class TestCreateWorkerGroupLinkTokenRequest(unittest.TestCase):
    """CreateWorkerGroupLinkTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWorkerGroupLinkTokenRequest:
        """Test CreateWorkerGroupLinkTokenRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWorkerGroupLinkTokenRequest`
        """
        model = CreateWorkerGroupLinkTokenRequest()  # noqa: E501
        if include_optional:
            return CreateWorkerGroupLinkTokenRequest(
                name = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CreateWorkerGroupLinkTokenRequest(
                name = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testCreateWorkerGroupLinkTokenRequest(self):
        """Test CreateWorkerGroupLinkTokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
