# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace.models.list_worker_groups200_response import ListWorkerGroups200Response  # noqa: E501

class TestListWorkerGroups200Response(unittest.TestCase):
    """ListWorkerGroups200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWorkerGroups200Response:
        """Test ListWorkerGroups200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWorkerGroups200Response`
        """
        model = ListWorkerGroups200Response()  # noqa: E501
        if include_optional:
            return ListWorkerGroups200Response(
                next = None,
                has_more = None,
                data = [
                    workspace.models.worker_group_resource.WorkerGroupResource(
                        id = '', 
                        name = '', )
                    ]
            )
        else:
            return ListWorkerGroups200Response(
                next = None,
                has_more = None,
                data = [
                    workspace.models.worker_group_resource.WorkerGroupResource(
                        id = '', 
                        name = '', )
                    ],
        )
        """

    def testListWorkerGroups200Response(self):
        """Test ListWorkerGroups200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
