# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace.models.asset_payload_empty_resource import AssetPayloadEmptyResource  # noqa: E501

class TestAssetPayloadEmptyResource(unittest.TestCase):
    """AssetPayloadEmptyResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetPayloadEmptyResource:
        """Test AssetPayloadEmptyResource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetPayloadEmptyResource`
        """
        model = AssetPayloadEmptyResource()  # noqa: E501
        if include_optional:
            return AssetPayloadEmptyResource(
                type = 'empty'
            )
        else:
            return AssetPayloadEmptyResource(
                type = 'empty',
        )
        """

    def testAssetPayloadEmptyResource(self):
        """Test AssetPayloadEmptyResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
