# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from workspace.models.asset_upload_completed_resource import AssetUploadCompletedResource  # noqa: E501

class TestAssetUploadCompletedResource(unittest.TestCase):
    """AssetUploadCompletedResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AssetUploadCompletedResource:
        """Test AssetUploadCompletedResource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AssetUploadCompletedResource`
        """
        model = AssetUploadCompletedResource()  # noqa: E501
        if include_optional:
            return AssetUploadCompletedResource(
                id = '',
                status = 'completed',
                content_type = ''
            )
        else:
            return AssetUploadCompletedResource(
                id = '',
                status = 'completed',
                content_type = '',
        )
        """

    def testAssetUploadCompletedResource(self):
        """Test AssetUploadCompletedResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
