[tool.robo]
name = "Browser"
description = "Example of browser automation that solves the RPA Challenge"
python = "3.10.12"

[tool.robo.dependencies]
robocorp="1.0.0"
robocorp-tasks="robocorp_tasks-2.2.0-py3-none-any.whl"
robocorp-browser="2.1.0"
robocorp-excel="0.4.0"
robocorp-http="0.4.0"
