# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2008_data import InlineResponse2008Data  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2008Data(unittest.TestCase):
    """InlineResponse2008Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2008Data(self):
        """Test InlineResponse2008Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2008_data.InlineResponse2008Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
