# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.process_api import ProcessApi  # noqa: E501


class TestProcessApi(unittest.TestCase):
    """ProcessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProcessApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_list_processes(self) -> None:
        """Test case for list_processes

        List processes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
