# coding: utf-8

"""
    Robocorp Control Room API

    Robocorp Control Room API

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.process_run_resource_started_by import ProcessRunResourceStartedBy  # noqa: E501

class TestProcessRunResourceStartedBy(unittest.TestCase):
    """ProcessRunResourceStartedBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessRunResourceStartedBy:
        """Test ProcessRunResourceStartedBy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessRunResourceStartedBy`
        """
        model = ProcessRunResourceStartedBy()  # noqa: E501
        if include_optional:
            return ProcessRunResourceStartedBy(
                type = 'api',
                details = openapi_client.models.process_run_resource_started_by_details.ProcessRunResource_started_by_details(
                    id = '', 
                    first_name = '', 
                    last_name = '', )
            )
        else:
            return ProcessRunResourceStartedBy(
                type = 'api',
                details = openapi_client.models.process_run_resource_started_by_details.ProcessRunResource_started_by_details(
                    id = '', 
                    first_name = '', 
                    last_name = '', ),
        )
        """

    def testProcessRunResourceStartedBy(self):
        """Test ProcessRunResourceStartedBy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
