name: Action Server Release - Sign and Deploy

on:
  workflow_dispatch:
    # Enables manual triggering via GitHub Actions

  # Run when build flow completes
  workflow_run:
    workflows: ["Action Server [BINARY] Release"]
    types:
       - completed

jobs:
  sign-macos:
    defaults:
      run:
        working-directory: ./action_server
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3