name: Metapackage Release

on:
  push:
    tags:
      - "robocorp-[0-9]+.[0-9]+.[0-9]+"

defaults:
  run:
    working-directory: './meta'

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry==1.7.1

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'poetry'

    - name: Install project
      run: poetry install

    - name: Check tag version
      run: poetry run invoke check-tag-version

    - name: Build with poetry
      run: poetry build

    - name: Upload to PyPI
      run: |
        poetry config pypi-token.pypi  ${{ secrets.PYPI_TOKEN_ROBOCORP_META }}
        poetry publish
